language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to install package
#install:
  - pip install setuptools --upgrade
#  - python setup.py install
  - pip install cli-github
# command to run tests
script:
  - nosetests
notifications:
  email: false
