language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install setuptools --upgrade
  - pip install cli-github
# command to run tests
script:
  - nosetests
notifications:
  email: false
